package cn.ghy.ps.project.service.grop;

import cn.ghy.ps.project.po.Grop;

import java.util.List;

/**
 * @author 穹镜
 * @date 2021/9/15 13:40
 * @描述
 */
public interface IGropService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grop
     *
     * @mbggenerated
     */
    int deleteByPrimaryKeys(String[] depId) throws Exception ;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grop
     *
     * @mbggenerated
     */
    int insertSelective(Grop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grop
     *
     * @mbggenerated
     */
    Grop selectByPrimaryKey(String depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_grop
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Grop record) throws Exception;

    /**
     *
     * @描述 分组列表
     *
     * @date 2021/9/15 13:39
     */
    List<Grop> selectGropList(Grop grop);

    /**
     * 校验分组名称是否唯一
     *
     * @param grop 分组信息
     * @return 结果
     */
    public String checkGropNameUnique(Grop grop);

    /**
     *
     * @描述: 查询所有分组下的所有用户 用户归类 树状数据
     *
     * @date: 2021/9/27 11:25
     */
    List<Grop> selectGropAndUser();
}
